### ISSUE TITLE
Plugin crashes on write if another response comes

### ISSUE THREAD

**Issue by Rikkun-1** [Rikkun-1/cypress-har-generator#1]
If application receives a new response after/during execution of then cy.saveHar command, then plugin crashes with the following error:
``` javascript
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

TypeError: Cannot read properties of undefined (reading 'write')
    at t.Plugin.<anonymous> (/home/torohov/projects/smsc/frontend/node_modules/@neuralegion/cypress-har-generator/dist/index.js:1:2252)
    at Generator.next (<anonymous>)
    at fulfilled (/home/torohov/projects/smsc/frontend/node_modules/tslib/tslib.js:115:62)
```

**Comment by Rikkun-1** [comment]
The problem was the following.

Plugin.saveHar calls Plugin.dispose
``` javascript
  public async saveHar(options: SaveOptions): Promise<void> {
    const filePath = join(options.outDir, options.fileName);

    this.assertFilePath(filePath);

    if (!this.connection) {
      this.logger.err(`Failed to save HAR. First you should start recording.`);

      return null;
    }

    try {
      await this.fileManager.createFolder(options.outDir);
      const har: string | undefined = await this.buildHar();

      if (har) {
        await this.fileManager.writeFile(filePath, har);
      }
    } catch (e) {
      this.logger.err(`Failed to save HAR: ${e.message}`);
    } finally {
      await this.dispose();
    }

    return null;
  }
```
Plugin.dispose unsubscribes, removes the buffer, and returns.
``` javascript
 public async dispose(): Promise<void> {
    await this.networkObservable?.unsubscribe();
    delete this.networkObservable;

    if (this.tmpPath) {
      await this.fileManager.removeFile(this.tmpPath);
      delete this.buffer;
    }
  }
```
But there is some delay before subscribe callback will be actually deleted.
In my case after test run plugin saves about har with size of 40mb.
App that I am testing makes requests each 0.5 seconds to update some numbers.
Saving file takes some time and in that time comes new response.
Callback tries to save new response to buffer and fails because buffer already got destroyed;

But there is some delay before callback is actually removed.
In my case, after a test run, the plugin saves about 40MB.
The app I'm testing sends requests every 0.5 seconds to update some numbers.
Saving the file takes some time, and during this time a new response arrives.
The callback tries to save the new response to the buffer and fails because the buffer has already been destroyed.

``` javascript
  private async listenNetworkEvents(options: RecordOptions): Promise<void> {
    this.buffer = await this.fileManager.createTmpWriteStream();
    this.networkObservable = new NetworkObserver(
      options,
      this.connection,
      this.logger
    );

    return this.networkObservable.subscribe(async (request: NetworkRequest) => {
      const entry = await new EntryBuilder(request).build();
      const entryStr = JSON.stringify(entry);
      this.buffer.write(`${entryStr}${EOL}`);
    });
  }
```

To investigate this I placed console.log like this.

``` javascript
  public async dispose(): Promise<void> {
    await this.networkObservable?.unsubscribe();
    delete this.networkObservable;
    console.log('unsubscribed and deleted networkObservable');

    if (this.tmpPath) {
      await this.fileManager.removeFile(this.tmpPath);
      delete this.buffer;
      console.log('removed Tempfile and deleted buffer');
    }
    return null;
  }

  private async listenNetworkEvents(options: RecordOptions): Promise<void> {
    this.buffer = await this.fileManager.createTmpWriteStream();
    this.networkObservable = new NetworkObserver(
      options,
      this.connection,
      this.logger
    );

    return this.networkObservable.subscribe(async (request: NetworkRequest) => {
      const entry = await new EntryBuilder(request).build();
      const entryStr = JSON.stringify(entry);
      console.log('buffer.write. is buffer exists: ' + (typeof this.buffer !== 'undefined'))
      this.buffer?.write(`${entryStr}${EOL}`);
    });
  }
```
This is what i got:
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
unsubscribed and deleted networkObservable
removed Tempfile and deleted buffer
buffer.write. is buffer exists: false // the application makes a request to update some numbers on the page every 0.5 seconds
// fails because buffer is undefined

// to fix that I placed optional chaining
``` javascript
  private async listenNetworkEvents(options: RecordOptions): Promise<void> {
    this.buffer = await this.fileManager.createTmpWriteStream();
    this.networkObservable = new NetworkObserver(
      options,
      this.connection,
      this.logger
    );

    return this.networkObservable.subscribe(async (request: NetworkRequest) => {
      const entry = await new EntryBuilder(request).build();
      const entryStr = JSON.stringify(entry);
        this.buffer?.write(`${entryStr}${EOL}`); // optional chaining
    });
  }
```

And now logs looks like this:
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
buffer.write. is buffer exists: true
unsubscribed and deleted networkObservable
removed Tempfile and deleted buffer
buffer.write. is buffer exists: false // the application makes a request to update some numbers on the page every 0.5 seconds
buffer.write. is buffer exists: false // don't crash because now buffer existence is checked before writing
buffer.write. is buffer exists: false
unsubscribed and deleted networkObservable
After this moment the app is still sending requests but callback finaly destroyed and nothing happens.
So it works as expected now.
